packages/msw-addon/src/mswDecorator.js
Thank you for making this awesome package! 
I was trying this out on a large project with lots of api calls and wanted to be able to warn or block unhandled request with the `onUnhandledRequest` argument for start.
I am not seeing any guidelines configured for this repo so please let me know if I should make any adjustments to this PR. 
Thanks!
=> Allow start options to be passed in

README.md, packages/docs/package.json, packages/docs/src/demos/apollo/App.stories.js, packages/docs/src/demos/apollo/App.test.js, packages/docs/src/demos/axios/App.stories.js, packages/docs/src/demos/axios/App.test.js, packages/docs/src/demos/fetch/App.stories.js, packages/docs/src/demos/fetch/App.test.js, packages/docs/src/demos/react-query/App.stories.js, packages/docs/src/demos/react-query/App.test.js, packages/docs/src/demos/react-router-react-query/App.stories.js, packages/docs/src/demos/react-router-react-query/pages/character/Character.stories.js, packages/docs/src/demos/react-router-react-query/pages/characters/Characters.stories.js, packages/docs/src/demos/react-router-react-query/pages/film/Film.stories.js, packages/docs/src/demos/react-router-react-query/pages/films/Films.stories.js, packages/docs/src/demos/urql/App.stories.js, packages/docs/src/demos/urql/App.test.js, packages/docs/src/guides/installation.stories.mdx, packages/docs/src/guides/introduction.stories.mdx, packages/msw-addon/README.md
This PR updates the stories files (as well as tests and documentation examples) to use [hoisted CSF](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#hoisted-csf-annotations) annotation which is the standard format since Storybook 6.
=> chore: update all stories to CSF hoisted format

packages/docs/netlify.toml
Setup Netlify redirect config so that when user visits `https://msw-sb.netlify.app/?path=/story/demos-axios--default-behavior` they are redirected to `https://msw-sb.vercel.app/?path=/story/demos-axios--default-behavior`.
Since we've removed Netlify integration from the repo, I've tested this using Netlify CLI. Try it out on 
https://60c97e618c2fb05148d83d8b--msw-sb.netlify.app
=> setup netlify to redirect to vercel

packages/msw-addon/package.json, packages/msw-addon/src/mswDecorator.js, yarn.lock
Using `esbuild` with Storybook leads to a failure using this add-on. This is because `esbuild` is a lot more strict and close to the spec.
This is the error : 
> Uncaught ReferenceError: global is not defined
To fix that I simply wrapper the check around a `try/catch`.
=> Failsafe environment check

CONTRIBUTING.md, package.json, packages/docs/src/demos/apollo/App.stories.js, packages/docs/src/demos/apollo/App.test.js, packages/docs/src/demos/axios/App.stories.js, packages/docs/src/demos/axios/App.test.js, packages/docs/src/demos/fetch/App.stories.js, packages/docs/src/demos/fetch/App.test.js, packages/docs/src/demos/react-query/App.stories.js, packages/docs/src/demos/react-query/App.test.js, packages/docs/src/demos/react-router-react-query/App.stories.js, packages/docs/src/demos/react-router-react-query/pages/character/Character.stories.js, packages/docs/src/demos/react-router-react-query/pages/characters/Characters.stories.js, packages/docs/src/demos/react-router-react-query/pages/film/Film.stories.js, packages/docs/src/demos/react-router-react-query/pages/films/Films.stories.js, packages/docs/src/demos/urql/App.stories.js, packages/docs/src/demos/urql/App.test.js, packages/msw-addon/src/mswDecorator.js
This PR does:
- Update all examples to use the new api. I quite like it
- Fix the storybook command in root package. I forgot to update the script name in the other PR
- Add a deprecation message when users set handlers directly to the `msw` parameter
=> Update addon usage in examples and add deprecation message

README.md, packages/docs/.storybook/manager-head.html, packages/docs/src/guides/introduction.stories.mdx, packages/msw-addon/package.json
Image links were broken after we switched from netlify to vercel, and I feel like we can just leverage the hosting platform of Github instead, so that we don't worry about stuff like this happening again :D
=> chore: replace logo image URLs

packages/msw-addon/package.json
This PR fixes peerDependencies to use current msw's version `v0.36.4`. 
https://github.com/mswjs/msw/releases
=> chore: fix "msw" peer dependency to 0.35.0 || 0.36.0

package.json, packages/docs/public/mockServiceWorker.js
- Fixes #66 
Attempts to resolve the following runtime error that, supposedly, happens when fetching the worker script:
```
A bad HTTP response code (404) was received when fetching the script.
```
=> fix: update the worker script

packages/msw-addon/src/mswDecorator.ts
Closes Require function is used in a way in which dependencies cannot be statically extracted #68
=> fix: webpack require warning

.github/workflows/release.yml, release.config.js
Adds a new "release" github workflow to automatically publish the addon to NPM every day.
=> chore: add "release" workflow

packages/msw-addon/package.json
Issue: #74
This PR proposes the following approach:
Set MSW as a peer dependency from 0.35 and higher minor versions.
The idea is that MSW is a peer dependency and will be managed by the users, which might want to try out new features and will always end up hitting a roadblock with this addon. In case MSW does release a breaking change as a minor, we will have to deal with it in the addon, which might be a good thing because it will force a faster evolution/sync of the addon
Thoughts @kettanaito ?
=> dep: expand msw peer dependency version range

packages/msw-addon/src/mswDecorator.ts
I really wanted to use MSW to reduce flakiness around placeholder images that would show up in chromatic snapshot tests. I suspected that a loader would help, and saw this PR, but in my testing the only way to ensure that requests for static assets that are sent on mount are properly mocked is to wait for the service worker startup to complete by waiting on this promise returned from `worker.start`.
=> Wait in loader for MSW to be fully ready

.github/workflows/release.yml
There have been recent releases of `semantic-release` which broke the default behavior of `cycjimmy/semantic-release-action@v2`:
```
Must use import to load ES Module: /home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/semantic-release/index.js
require() of ES modules is not supported.
```
They get fixed either by upgrading the action or specifying semantic-release version to be 19.
=> chore: Upgrade `cycjimmy/semantic-release-action` to v3

.github/workflows/chromatic.yml, .github/workflows/release.yml, .gitignore, packages/msw-addon/package.json, yarn.lock
This PR changes from semver to [auto](https://intuit.github.io/auto/) for easier release management. It also adds a way to make prereleases if necessary.
=> Use auto for release management

packages/docs/src/demos/fetch/App.jsx, packages/docs/src/demos/fetch/App.stories.jsx, packages/msw-addon/src/mswDecorator.ts
Now that @storybook/react-native has reached compatibility with storybook 6, it supports CSF, which means we can _almost_ use this decorator for react native storybooks!
There's just one missing piece: the `initialize` function needs to call `setupServer` from `msw/native` in a ReactNative environment. Credit to [this post](https://phelipetls.github.io/posts/using-storybook-and-msw-in-react-native/) for that part.
This PR adds a special case for react native next to the existing DOM and Node initialization code.
=> Feature: Support React Native environments

packages/docs/src/guides/introduction.mdx
With this pull request, the documentation was updated to fix the currently existing broken links in the documentation and a minor issue with the navigation, which was causing Storybook to show a non-existing story/docs page.
Looking forward to hearing your feedback.
Hope y'all have a fantastic weekend.
Stay safe
=> Docs: Minor updates to links and navigation issue

packages/msw-addon/package.json, packages/msw-addon/src/applyRequestHandlers.ts, packages/msw-addon/src/augmentInitializeOptions.ts, packages/msw-addon/src/decorator.ts, packages/msw-addon/src/index.ts, packages/msw-addon/src/initialize.browser.ts, packages/msw-addon/src/initialize.node.ts, packages/msw-addon/src/initialize.react-native.ts, packages/msw-addon/src/loader.ts, packages/msw-addon/tsconfig.json, packages/msw-addon/tsup.config.ts
this updates conditional exports so that both types and dependencies can be resolved.
this also migrates build to generating esm by default for a more standards based packaging approach with strong support in modern tooling like webpack and vite.
resolves #137
This draws from https://www.typescriptlang.org/docs/handbook/modules/theory.html#module-resolution-for-libraries
which recommends node16 resolution for libraries, which has the strictest resolution rules, which should work for almost all downstream adopters.
Follows similar ESM conventions to https://github.com/sindresorhus/meta/discussions/15
There are still a few quirks in legacy build tools (mostly webpack 4) https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c those generally should not impact storybook builds
=> feat!(msw-addon): fix package exports and generate esm build

packages/msw-addon/src/loader.ts
If msw is running in fallback mode, navigator.serviceWorker may not be defined.
https://github.com/mswjs/msw-storybook-addon/pull/122
=> fix(loader.ts): fix possible undefined

packages/docs/package.json, packages/msw-addon/package.json, packages/msw-addon/tsup.config.ts, yarn.lock
Fixes #145
<details>
<summary>📦 Published PR as canary version: <code>2.0.1--canary.152.93758da.0</code></summary>
<br />
:sparkles: Test out this PR locally via:
```bash
npm install msw-storybook-addon@2.0.1--canary.152.93758da.0
yarn add msw-storybook-addon@2.0.1--canary.152.93758da.0
```
</details>
=> Fix: Use CJS for node entrypoint

packages/msw-addon/src/decorator.ts
The type does not seem to match the docs which say:
```typescript
type MswParameter = {
handlers: RequestHandler[] | Record<string, RequestHandler | RequestHandler[]>
}
```
[ref](https://storybook.js.org/addons/msw-storybook-addon#composing-request-handlers)
=> Fix `MswParameters` handlers type

packages/msw-addon/src/decorator.ts
Previously, this was only communicated to the user via the browser console, and so was easy to miss. I only noticed it because of reading the changelog.
It'll be much more likely for users to notice this deprecation if their editor tells them that it's deprecated, so this will hopefully help ease migration.
=> fix: add a `@deprecated` tag to the `mswDecorator`
